# 1. Create a NumPy array of integers from 1 to 10

In [18]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2. Create a 2x3 NumPy array filled with zeros.


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# 3. Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr2=np.arange(2,21,2)

In [ ]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# 4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

# 5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.


In [ ]:
arr3=np.random.randint(0,100,100)
np.mean(arr3)

48.32

In [ ]:
np.median(arr3)

44.5

In [ ]:
np.std(arr3)

29.08981952505034

# 6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr4=np.random.randint(0,30,12)
arr5=arr4.reshape(3,4)
arr5

array([[ 9, 23, 24, 29],
       [25, 23, 26, 19],
       [ 7, 16, 25,  3]])

# 7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [ ]:
arr=np.array([1,2,3,4,5])
np.square(arr)

array([ 1,  4,  9, 16, 25])

# 8. Create a 5x5 identity matrix using NumPy.

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6])

In [ ]:
a=np.array([1, 2, 3])
b = np.array([4, 5, 6])
a.dot(b)

32

# 10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [19]:
arr9=([1,2,3,8,9,10])
np.argmax(arr9)

5

In [20]:
np.argmin(arr9)

0

# 11.Concatenate two random NumPy arrays horizontally and vertically

In [ ]:
arr10=np.random.randint(2)
arr11=np.random.randint(2)
np.hstack((arr10,arr11))

array([0, 0])

In [ ]:
np.vstack((arr10,arr11))

array([[0],
       [0]])

# 12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [ ]:
arr12=np.arange(1,10)
np.sum(arr12)

45

# 13.Find the common elements between two NumPy arrays

In [26]:
arr13=np.array([[1,10],[2,9],[1,3]])
arr14=np.array([[1,3],[2,4],[8,5]])
np.intersect1d(arr13,arr14)

array([1, 2, 3])

# 14.Replace all negative values in a NumPy array with zeros.

In [ ]:
arr15=np.array([-3,-2,-1,0,1,2,3])
arr15[arr15<0]=0
arr15

array([0, 0, 0, 0, 1, 2, 3])

# 15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.


In [27]:
arr=np.random.randint(1,100,5)
np.sort(arr)

array([ 1, 18, 20, 23, 24])

# 16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [23]:
arr16=np.array([1,2,3])
arr17=np.array([4,5,6])
np.absolute(arr16,arr17)

array([1, 2, 3])

# 17.Given a 2D NumPy array, extract the first row and the last column.

In [35]:
arr18=np.array([[1,2],[6,7],[8,9]])
arr18[:,0]

array([1, 6, 8])

In [36]:
arr18[:,1]

array([2, 7, 9])

# 18.Slice a 1D NumPy array to get every other element.

In [ ]:
arr19=np.array([1,2,3,4])
arr19[1:4]

array([2, 3, 4])

# 19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [ ]:
arr20=np.array([[1,2,3],
               [4,5,6,],
              [7,8,9]])
arr20[:2,:2]

array([[1, 2],
       [4, 5]])

# 20.Reverse a 1D NumPy array using slicing

In [ ]:
arr21=np.array([[1,2,3]])
arr21[::-1]

array([[3, 2, 1]])